name = "GaussianBeamLens"
uuid = "270b4de7-9982-4ec9-82b5-5a39cab38fbe"
authors = ["Raghav Chhetri <chhetrir@janelia.hhmi.org>", "Mark Kittisopikul <kittisopikulm@janelia.hhmi.org>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
